version: '3'
services:
  cart:
    build: './cart'
    ports:
      - "3001:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=${DB_CONNECT}

  category:
    build: './category'
    ports:
      - "3002:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=${DB_CONNECT}

  order:
    build: './order'
    ports:
      - "3003:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=${DB_CONNECT}

  product:
    build: './product'
    ports:
     - "3004:3000"
    depends_on: 
    - db
    environment:
    - MONGO_DB_URI=${DB_CONNECT}
  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cart
      - category
      - order
      - product
